#!/usr/bin/env pybricks-micropython
from robot import *
# Write code here
ilan = Robot()
ilan.reset_wall()
ilan.beep()
#ilan.wall_x_motor.run_time(200,3000,Stop.COAST,True)
wait(1000)
def go_trucks():
    ilan.move_wall_to_point(ilan.WALL_MAX_ANGLE_X, ilan.WALL_MAX_ANGLE_Y)
    wait(2000)
    ilan.move_wall_to_point(ilan.WALL_MAX_ANGLE_X, 70)
    print("x = " + str(ilan.wall_x_motor.angle()) + ", y = " + str(ilan.wall_y_motor.angle()))
    ilan.beep()
    print("going")
    ilan.pid_gyro(10,100)
    ilan.move_wall_to_point(ilan.WALL_MAX_ANGLE_X, 50)
    ilan.pid_follow_line(ilan.color_sensor_right,68,120,1.3, True)
    ilan.beep()
    ilan.move_wall_to_point(670, ilan.WALL_MAX_ANGLE_Y)
    ilan.pid_gyro(30,100)
    ilan.move_wall_to_point(670, 150)
    ilan.pid_gyro(13,100)
    ilan.move_wall_to_point(x=670, y=50)
    ilan.move_wall_to_point(x=670, y=ilan.WALL_MAX_ANGLE_Y)
    ilan.pid_gyro(30, 50)
    ilan.move_wall_to_point(x=670, y=0)
    ilan.pid_gyro(-5, 50)
    # # ilan.robot.turn(-90)
    # ilan.pid_gyro(20)
    # #ilan.pid_follow_line(ilan.color_sensor_right,20,120,1.5, True)
    # #ilan.move_wall_to_point(ilan.WALL_MAX_ANGLE_X,ilan.WALL_MAX_ANGLE_Y)  
    # ilan.beep()
go_trucks()
